@startuml

class Scene {
  idScene: int
  nomScene: string
  descriptionScene: string
  lienVignetteImage: string
  lienExecutable: string
  dateAjout: datetime
  lienImage: string
  equipe: int
}

class Utilisateur {
  idUser: int
  nomUser: string
  mail: string
  password: string
  admin: boolean
  lienAvatar: string
}

class Commentaire {
  idCom: int
  titre: string
  corpsDuCommentaire: string
  dateCreation: datetime
  dateModif: datetime
}

class Note{
   valeur: int
}

class Favori {
  utilisateur: Utilisateur
  scenes: List<Scene>
}

Utilisateur  --  Commentaire : commente

Scene  --  Commentaire : concerne

(Utilisateur, Scene) .. Note

(Utilisateur, Scene) .. Favori


@enduml
