@startuml


class Scene {
  idScene: int
  --
  nomScene: string
  description: string
  lienVignetteImage: string
  lienExecutable: string
  dateAjout: datetime
  descriptionScene: string
  lienImage: string
  equipe: int
}

class Utilisateur {
  idUser: int
  --
  nomUser: string
  mail: string
  password: string
  admin: boolean
  avatar: string
}

class Commentaire {
  idCom: int
  --
  titre: string
  corpsDuCommentaire: string
  dateCreation: datetime
  dateModif: datetime
}

class Note{
  idUser: int <FK>
  idScene: int
  --
  note: int
}

class Favori {
  idUser: int
  idScene: int
}

Utilisateur "1" --> "0..*" Scene
Utilisateur "1" --> "0..*" Commentaire
Utilisateur "1" --> "1" Note
Utilisateur "1" --> "0..*" Favori

Scene "1" --> "0..*" Commentaire
Scene "1" --> "0..*" Favori
Scene "1" --> "0..*" Note

@enduml
